---
title: "Centering Treatments"
author: "Art Eschenlauer"
date: "11/16/2019"
output:
  pdf_document:
    highlight: null
    number_sections: no
    toc: no
    toc_depth: 4
  html_document:
    df_print: paged
    toc: no
    toc_depth: '4'
  knitr:::html_vignette:
    fig_caption: yes
    toc: no
    toc_depth: 4
subtitle: Advanced function for 'W4M Data Subset'
vignette: |
  %\VignetteIndexEntry{Centering Treatments}
  \usepackage[utf8]{inputenc}
  \usepackage[all]{nowidow}
  \widowpenalty10000
  \clubpenalty10000
  %\VignetteEngine{knitr::rmarkdown}
# build vignette with rmarkdown::render("vignettes/centering-enhancement.Rmd", "all")
---

# Summary

This document describes an extension to convert a data matrix for a replicated design to a data matrix having one column per treatment.   

## Motivation

W4M does not have tools to contrast treaments *per se*.  Sample metadata annotations can indicate replicates of a common treatment, but sometimes predictive tools like Heat Map (i.e., hierarchical clustering) and Multivariate (running as PLS-DA) assign different predicted treatments to samples from the same treatment.  This confounds examination of relationships among the treatments themselves.

With an appropriate output mode, this extension collapses a data matrix having one column per sample to a data matrix having one column per treatment, where column is the "center" for the respective set of replicates for that treatment.  

## Choices

### Choice of median versus mean

Although normally distributed data could be analayzed using mean and standard deviation respectively for assessment of the center and the spread, I see no advantage of not treating all data as having an unknown distribution and using median to estimate the center and the median absolute deviation or Mahalanobis distance to estimate the spread.

### Choice of input to covariance calculation

The number of cells in the covariance matrix is the square of the number of features, and its computation increases linearly with the number of samples.

I chose to use a single computation of the covariance matrix to save computation time and ensure that all distances are computed for the same basis.  Perhaps I can by:

- Compute the covariance matrix $\textbf{S}_{centers}$ for the matrix of sample-centers $\times$ features.
    - Because this spans all treatments but minmizes the influence of outliers, it should capture the full range of variation of the features and, hence, provide a complete representation of the span of their covariation.
- For computing the Mahalanobis distance for treatment $i$ it is necessary to apply an appropriately scaled $\textbf{S}_{i}$, obtained by dividing $\textbf{S}_{centers}$ by $n_{centers}$ and multiplying by $n_i$.

## Center of data with an unknown (possibly normal) distribution

For data having an unknown (possibly normal) distribution, for each of $m$ treatments $i$ and each of $n_i$ samples $k$ for each feature $j$:

$$ \text{center}_{{treatment_i},{intensity_j}} = median(intensity_{i,j,k} \; \forall k \in [1,n_i]) $$ 
$$ \text{distance}_{treatment_i} = \sqrt{\sum_{r=1}^j \Big(mad(intensity_{i,r,k} \; \forall k \in [1,n_i])\Big)^2} $$
$$ \text{center}_{overall,{intensity_j}} = median(\text{center}_{{treatment_i},{intensity_j}} \; \forall i \in [1,m]) $$ 
$$ \text{distance}_{overall} = \sqrt{\sum_{r=1}^m \Big(mad(\text{center}_{{treatment_i},{intensity_r}})\Big)^2} $$
$$ \text{$D^{\circ}$}_{treatment_i} = \frac{\text{distance}_{treatment_i}}{\text{distance}_{overall}}$$

## Most representative sample for each treatment

In summary, compute the center for each treatment, then choose as the sample closest to the center that sample which has the lowest Mahalanobis distance (which takes into account covariance among the features.)

### Robust inverse covariance

First, compute $\textbf{S}$, **the "Minimum Covariance Determinant" of the data matrix $\textbf{X}$**, and its inverse $\textbf{S}^{-1}$, using `MASS::cov.mcd` ([https://stat.ethz.ch/R-manual/R-patched/library/MASS/html/cov.rob.html](https://stat.ethz.ch/R-manual/R-patched/library/MASS/html/cov.rob.html)):
$$\textbf{S} = \text{MASS::cov.mcd}(\textbf{X}), \quad \textbf{S}^{-1} = (\textbf{S})^{-1}$$

### For each treatment $i$:

First compute **the center for the $n_i$ samples from $treatment_i$**:
$$\vec{c}_i = \text{center}_{{treatment_i}} = median\Big(intensity_{i,j,k} \; \forall k \in [1,n_i]\Big) \; \forall j$$

Next, for each sample $k$ from $treatment_i$, compute **the Mahalanobis distance to $\vec{c}_i$ from the location $\vec{x}_{i,k}$** (`stats::mahalonobis`, [https://stat.ethz.ch/R-manual/R-patched/library/stats/html/mahalanobis.html](https://stat.ethz.ch/R-manual/R-patched/library/stats/html/mahalanobis.html)):
$$\begin{aligned}
D_M(\vec{x}_{i,k},\vec{\text{c}}_i)
= \sqrt{(\vec{\text{residual}_{i_k}})^T S^{-1} (\vec{\text{residual}_{i_k}})} \; \Big| \; \vec{{\text{residual}_{i_k}}} = \vec{x}_{i,k}-\vec{c}_{i,k} \\
= \sqrt{\text{stats::mahalanobis}(\text{x} = \vec{x}_{i,k}, \text{center} = \vec{\text{c}}_i, \text{cov} = \textbf{S}^{-1}, \text{inverted} = \text{TRUE})}
\end{aligned}$$

Next, choose the sample with the lowest $D_M$ as **the most representative sample for the treatment.**
$$\vec{c}_i = \text{center}_{\text{treatment}_i,\text{intensity}_j} \forall j$$

Next, compute **the Mahalanobis distance across the treatment** using the $\textbf{x}_i$, the $n_i \times j$ slice of the data matrix for samples subjected to treatement $i$
$$D_M(\textbf{x}_{i},\vec{\text{c}}_i)
= \sqrt{\text{stats::mahalanobis}(\text{x} = \textbf{x}_{i}, \text{center} = \vec{\text{c}}_i, \text{cov} = \textbf{S}^{-1}, \text{inverted} = \text{TRUE})}
$$

### Overall center and Mahalanobis distance:

Compute **the center for all $m$ treatments $i$** 
$$ \vec{c} = \text{center}_\text{overall} = mean({\vec{c}_i} \; \forall i \in [1,m]) $$ 

Next, bind the centers $\vec{c}_i$ into an $m \times j$ matrix $\textbf{c}$, and then **compute the overall Mahalanobis distance among all the treatments**.
$$D_{M,\text{overall}}
= \sqrt{\text{stats::mahalanobis}(\text{x} = \textbf{c}, \text{center} = \vec{c}, \text{cov} = \textbf{S}^{-1}, \text{inverted} = \text{TRUE})}
$$

### For each treatment $i$:

Finally, compute **the relative dispersion for each treatment $i$** (analogous to a D-ratio):
$$ \text{$D^{\bullet}$}_{treatment_i} = \frac{D_M(\textbf{x}_{i},\vec{\text{c}}_i)}{D_{M,\text{overall}}}$$

## Options for output

Depending on the output mode, the resulting treatment metadata include the following column:

- `trt`, the name of the treatment (i.e., the content of a specified column from `sampleMetadata`)
- `n`, the number of replicates for the treatment
- `d_dot` ($D^{\circ}$ or $D^{\bullet}$), the spread of the replicates for the treatment relative to the spread between the treatments (analogous to D--ratio).
- `d_mc` ($D_{M_{center_i}}$), the Mahalanobis distance between the sample and the center for treatment $i$.

Implemented presently:

- Behave as `center` immediately below.

Planned, along with a choice dropdown:

- `center` - replace all replicates of a treatment with the center for the treatment.
- `append` - append the treatment centers to the samples.  Set `n` and `D_dot` for samples to `NA`.  This might be useful to calculate the distance between samples and (their own or other) treatment centers.
- `annotate` - do not replace samples.  Set `n` and `D_dot` to `NA` for all replicates for a treatment except the replicate nearest to its treatment center. 

Abandoned:

- `nearest` - replace all replicates with the replicate nearest to its treatment center.


## Confidence Interval for the median

Note that the Kibria (2006) evaluates the `median t` confidence interval for the *mean* of an assymetric distribution, defined as:

$$ \bar{x} \pm t_{\frac{\alpha}{2},n-1} \frac{\tilde{s}_1}{\sqrt{n}} \; \Bigg| \; \tilde{s}_1 = \sqrt{\frac{1}{n-1} \sum_{i=1}^n (x_i - \tilde{x})^2}, \tilde{x} = \text{sample median}$$

Presumably, the confidence interval for the *median* would be centered on the sample median:

$$ {\bf\tilde{x}} \pm t_{\frac{\alpha}{2},n-1} \frac{\tilde{s}_1}{\sqrt{n}} \; \Bigg| \; \tilde{s}_1 = \sqrt{\frac{1}{n-1} \sum_{i=1}^n (x_i - \tilde{x})^2}, \tilde{x} = \text{sample median}$$

## References

Kibria, B. M. Golam (2006) **Modified confidence intervals for the mean of the Asymmetric distribution.** Pakistan Journal of Statistics. **22**(2): 109-120.
